version: '3.8'

services:
  # 后端API服务 (开发模式)
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    environment:
      - CORP_ID=${CORP_ID}
      - CORP_SECRET=${CORP_SECRET}
      - AGENT_ID=${AGENT_ID}
      - FRONTEND_URL=http://localhost:3000
      - DEBUG=True
      - HOST=0.0.0.0
      - PORT=5000
      - SECRET_KEY=dev-secret-key
    volumes:
      - ./api:/app
      - /app/__pycache__
    restart: unless-stopped
    command: python app.py

  # 前端服务 (开发模式)
  web:
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5000
      - NEXT_PUBLIC_APP_NAME=企业微信应用
      - NEXT_PUBLIC_APP_VERSION=1.0.0
    volumes:
      - ./web:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - api
    restart: unless-stopped
    command: npm run dev
